

insert into cliente (id_cliente, nombre, direccion, rfc) values (1, 'Eberto MacKowle', 'Guanajuato', 'H11823');
insert into cliente (id_cliente, nombre, direccion, rfc) values (2, 'Tuckie Semark', 'Tamaulipas', 'S42102D');
insert into cliente (id_cliente, nombre, direccion, rfc) values (3, 'Flory Zannutti', 'Tamaulipas', 'T447X5S');
insert into cliente (id_cliente, nombre, direccion, rfc) values (4, 'Bridgette Helks', 'Chiapas', 'S66392A');
insert into cliente (id_cliente, nombre, direccion, rfc) values (5, 'Lucas Challinor', 'Chihuahua', 'S40862');
insert into cliente (id_cliente, nombre, direccion, rfc) values (6, 'Beatriz Thornley', 'Oaxaca', 'T7805');
insert into cliente (id_cliente, nombre, direccion, rfc) values (7, 'Ranna Sibbit', 'Guerrero', 'Q9388');
insert into cliente (id_cliente, nombre, direccion, rfc) values (8, 'Anita Bruntjen', 'Guanajuato', 'S99039S');
insert into cliente (id_cliente, nombre, direccion, rfc) values (9, 'Humphrey McEwen', 'Oaxaca', 'T63431');
insert into cliente (id_cliente, nombre, direccion, rfc) values (10, 'Demetria Magill', 'Chiapas', 'S82199M');
insert into cliente (id_cliente, nombre, direccion, rfc) values (11, 'Vinita Veldstra', 'Chiapas', 'D529');
insert into cliente (id_cliente, nombre, direccion, rfc) values (12, 'Matilda Yurenev', 'Tamaulipas', 'M6146');
insert into cliente (id_cliente, nombre, direccion, rfc) values (13, 'Nathalia Wearden', 'Guerrero', 'G90522');
insert into cliente (id_cliente, nombre, direccion, rfc) values (14, 'Brook Grogono', 'Guanajuato', 'K8510');
insert into cliente (id_cliente, nombre, direccion, rfc) values (15, 'Shell Jellyman', 'Tamaulipas', 'S31051');
insert into cliente (id_cliente, nombre, direccion, rfc) values (16, 'Margery Barrowcliff', 'Chiapas', null);
insert into cliente (id_cliente, nombre, direccion, rfc) values (17, 'Arnie Devanney', 'Guanajuato', 'S4452');
insert into cliente (id_cliente, nombre, direccion, rfc) values (18, 'Salomone Titmus', 'Chiapas', 'S63509S');
insert into cliente (id_cliente, nombre, direccion, rfc) values (19, 'Gavra Garlett', 'Chihuahua', 'B3881');
insert into cliente (id_cliente, nombre, direccion, rfc) values (20, 'Cindi Cockings', 'Chiapas', 'O3451');
insert into cliente (id_cliente, nombre, direccion, rfc) values (21, 'Dieter Dobbin', 'Oaxaca', 'H02812');
insert into cliente (id_cliente, nombre, direccion, rfc) values (22, 'Gran Putland', 'Tamaulipas', 'S43109D');
insert into cliente (id_cliente, nombre, direccion, rfc) values (23, 'Maxim Arstall', 'Coahuila De Zaragoza', 'S22020B');
insert into cliente (id_cliente, nombre, direccion, rfc) values (24, 'Lulu Joscelin', 'Tamaulipas', 'S62323');
insert into cliente (id_cliente, nombre, direccion, rfc) values (25, 'Richie Daugherty', 'Durango', 'X990XXS');
insert into cliente (id_cliente, nombre, direccion, rfc) values (26, 'Myrtice Dowse', 'Guerrero', 'S36439A');
insert into cliente (id_cliente, nombre, direccion, rfc) values (27, 'Angel Whewell', 'Guanajuato', 'M89412');
insert into cliente (id_cliente, nombre, direccion, rfc) values (28, 'Aggi Ramirez', 'Chihuahua', 'H59121');
insert into cliente (id_cliente, nombre, direccion, rfc) values (29, 'Belita Stack', 'Chiapas', 'N644');
insert into cliente (id_cliente, nombre, direccion, rfc) values (30, 'Pablo Turn', 'Guanajuato', null);
insert into cliente (id_cliente, nombre, direccion, rfc) values (31, 'Sid Eberz', 'Coahuila De Zaragoza', null);
insert into cliente (id_cliente, nombre, direccion, rfc) values (32, 'Hercules Lasslett', 'Guanajuato', 'T23521S');
insert into cliente (id_cliente, nombre, direccion, rfc) values (33, 'Clementina Joney', 'Tamaulipas', 'S62033G');
insert into cliente (id_cliente, nombre, direccion, rfc) values (34, 'Marnie Minchell', 'Chiapas', 'M89421');
insert into cliente (id_cliente, nombre, direccion, rfc) values (35, 'Abbe Blyth', 'Oaxaca', 'S60467A');
insert into cliente (id_cliente, nombre, direccion, rfc) values (36, 'Celestyna Thame', 'Guerrero', 'S02102A');
insert into cliente (id_cliente, nombre, direccion, rfc) values (37, 'Ricki O''Crowley', 'Chihuahua', 'S9410');
insert into cliente (id_cliente, nombre, direccion, rfc) values (38, 'Mose Yeulet', 'Coahuila De Zaragoza', 'S63247S');
insert into cliente (id_cliente, nombre, direccion, rfc) values (39, 'Kizzee Brigstock', 'Chiapas', 'Q649');
insert into cliente (id_cliente, nombre, direccion, rfc) values (40, 'Bennie Jodlowski', 'Chihuahua', 'S62226S');
insert into cliente (id_cliente, nombre, direccion, rfc) values (41, 'Theodora Guyot', 'Guanajuato', 'S61337A');
insert into cliente (id_cliente, nombre, direccion, rfc) values (42, 'Filippa Sangster', 'Guerrero', null);
insert into cliente (id_cliente, nombre, direccion, rfc) values (43, 'Gael Bloxsom', 'Tamaulipas', 'M2461');
insert into cliente (id_cliente, nombre, direccion, rfc) values (44, 'Katerina Gannaway', 'Chihuahua', 'M7155');
insert into cliente (id_cliente, nombre, direccion, rfc) values (45, 'Ivonne Slimon', 'Chiapas', 'S56302D');
insert into cliente (id_cliente, nombre, direccion, rfc) values (46, 'Chris Skelding', 'Chiapas', 'H59029');
insert into cliente (id_cliente, nombre, direccion, rfc) values (47, 'Jeremie Owttrim', 'Coahuila De Zaragoza', 'T65292');
insert into cliente (id_cliente, nombre, direccion, rfc) values (48, 'Tobe Willimont', 'Chiapas', 'V00282S');
insert into cliente (id_cliente, nombre, direccion, rfc) values (49, 'Melvyn Ibert', 'Tamaulipas', 'V9018XA');
insert into cliente (id_cliente, nombre, direccion, rfc) values (50, 'Sterne But', 'Tamaulipas', 'F949');