insert into  factura  (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico,Cliente_id_cliente,Cliente_rfc)  values  (1,'5/10/2022','Yuan Renminbi','bnanelli0@slate.com',1,'T458X6D ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(2,'5/7/2022','Real','adales1@hexun.com',2,'L02233  ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(3,'1/26/2022','Peso','gattewill2@vkontakte.ru',3,'S8253XP ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(4,'7/10/2022','Yuan Renminbi','gcrutch3@so-net.ne.jp',4,'S63277D ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(5,'7/9/2022','Zloty','knuss4@goodreads.com',5,'B9681   ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(6,'2/12/2022','Yuan Renminbi','pdaventry5@xing.com',6,'S82464C ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(7,'5/29/2022','Yuan Rei','tbullant6@house.gov',7,'Y92190  ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(8,'4/6/2022','Yuan i','bbelch7@tiny.cc',8,'S59012G ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(9,'2/21/2022','Dollar','rbeak8@yolasite.com',9,'T590X4D ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(10,'1/28/2022','Rial','cmcfadyen9@infoseek.co.jp',10,'S53429S ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(11,'5/12/2022','Yuan Ecc','adearnleya@youku.com',11,'H9012   ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(12,'9/15/2022','Rupiah','amarnerb@nifty.com',12,'S82392R ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(13,'5/12/2022','Peso','lmcneicec@multiply.com',13,'S39013S ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(14,'3/18/2022','Franc','clabbetd@arizona.edu',14,'S83106A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(15,'10/28/2022','Yuan Rdfd','lnernee@rambler.ru',15,'T84498S ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(16,'8/24/2022','Hryvnia','rmartinhof@fda.gov',16,'S75901A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(17,'3/7/2022','Escudo','chaskellg@so-net.ne.jp',17,'S73032A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(18,'4/1/2022','Ruble','jrodieh@nps.gov',18,'V857XXA ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(19,'8/6/2022','Rupiah','kdruryi@github.com',19,'M79A9   ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(20,'7/31/2022','Euro','skenderj@cnn.com',20,'M84629G ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(21,'11/10/2022','Euro','shinschk@chronoengine.com',21,'DFSDFGD ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(22,'1/8/2022','Rupiah','ttoyel@home.pl',22,'Y36311A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(23,'5/21/2022','Boliviano','gnasonm@g.co',23,'M05532  ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(24,'10/15/2022','Zloty','cshermarn@cyberchimps.com',24,'M1A0520 ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(25,'6/7/2022','Peso','aavramovo@spiegel.de',25,'S01111S ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(26,'10/28/2022','Real','spridiep@w3.org',26,'T22199A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(27,'2/26/2022','Dollar','tleathersq@twitter.com',27,'S62009G ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(28,'11/15/2022','Dollar','gclemotr@yahoo.co.jp',28,'M84475G ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(29,'1/31/2022','Krona','yvanshins@auda.org.au',29,'S06330A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(30,'11/23/2022','Pound','hthurbornt@histats.com',30,'R402253 ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(31,'5/28/2022','Peso','malliboneu@macromedia.com',31,'S8252XB ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(32,'6/19/2022','Euro','eburdfieldv@free.fr',32,'M8633   ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(33,'3/24/2022','Peso','vtoolanw@free.fr',33,'T24729A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(34,'5/17/2022','Peso','mduchennex@is.gd',34,'J151    ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(35,'8/5/2022','Yen','adutty@exblog.jp',35,'A5059   ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(36,'10/31/2022','Peso','kgorthyz@upenn.edu',36,'S66892D ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(37,'6/11/2022','Koruna','rvernau10@reddit.com',37,'H1583   ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(38,'1/26/2022','Lempira','bsquirrel11@tamu.edu',38,'D571    ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(39,'9/24/2022','Rupiah','jsudworth12@hexun.com',39,'S65019S ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(40,'4/10/2022','Yuan Ffdf','khindenberger13@csmonitor.com',40,'S20349A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(41,'10/16/2022','Euro','csidgwick14@tuttocitta.it',41,'L03116  ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(42,'1/8/2022','Real','smccready15@paypal.com',42,'S80821A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(43,'3/2/2022','Som','dterbeek16@berkeley.edu',43,'W3301XD ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(44,'3/16/2022','Yuan bi','tmidson17@paginegialle.it',44,'S60561  ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(45,'11/11/2022','Peso','ckrienke18@a8.net',45,'W5321XA ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(46,'5/1/2022','Euro','gvelden19@cbc.ca',46,'S548X2A ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(47,'6/24/2022','Yuani Sdsd','mcossons1a@jiathis.com',47,'S65519D ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(48,'11/11/2022','Ruble','nmearing1b@ustream.tv',48,'H401324 ');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(49,'3/28/2022','Som','qmilier1c@psu.edu',49,'DSAASDFS');
insert into factura (id_factura ,fecha_cobro  ,modo_pago  ,correo_electronico  ,Cliente_id_cliente,Cliente_rfc)values(50,'8/4/2022','Kuna''rbond1d@wix.com',50,'S82464B ');
